# Generated by Django 5.0.9 on 2026-09-12 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_make_middle_about_fields_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about_journey',
            field=models.TextField(blank=True, help_text='Second paragraph of the About section.'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='about_technical',
            field=models.TextField(blank=True, help_text='Third paragraph of the About section.'),
        ),
    ]
